import { isGeneric, Choice, Sequence } from './graph.js';
import type {
  Graph, GraphToken, GraphCollection, StandaloneOperator, StateKey, StateName, IterationOperator, Generic
} from './graph.js';
import type { SccId } from './scc.js';
import { MapView } from './shared.js';
import { logic, type Resources, type Fn } from './emit.js';

export type ResultValue =
  | Result
  | Result[]
  | MatcherValue
  | null;

export type BaseResult = {
  ok: boolean;
  pos: number;
  value: ResultValue;
  ws?: MatcherValue | null;
};
export type Result =
  | BaseResult & { type: 'none'; ok: false; value: null; }
  | BaseResult & { type: 'lookahead'; positive: boolean; value: Result; }
  | BaseResult & { type: 'state'; state: StateName; value: Result; }
  | BaseResult & { type: 'choice'; value: Result; alt: number | null; }
  | BaseResult & { type: 'sequence'; value: Result[]; }
  | BaseResult & { type: 'terminal'; value: MatcherValue; ok: true; }
  | BaseResult & { type: 'terminal'; value: null; ok: false; }
  | BaseResult & { type: 'iteration'; kind: IterationOperator; value: Result[]; }
  | BaseResult & { type: 'rewind'; value: Result; }
  | BaseResult & { type: 'root'; trailing_ws: MatcherValue | null; value: Result & { type: 'state'; }; };

export type MatcherValue = string;

export type SkipWsFn<K extends StateName, WS_C> = (rc: RuntimeCtx<K, WS_C>, pos: number) => [ws: MatcherValue | null, pos: number];
export type SkipWs<K extends StateName, WS_C> = Fn<SkipWsFn<K, WS_C>>;

type MemoEntry = { result: Result; };
interface ParserCtx<K extends StateName, WS_C> {
  readonly graph: Graph<K>;

  readonly sccOf: MapView<StateKey<K>, SccId>;
  readonly sccMembers: MapView<SccId, StateKey<K>[]>;
  readonly sccSolvers: Map<SccId, Fn<FnT<K, WS_C, void>>>;

  readonly lexicalStates: Set<StateKey<K>>;
  readonly stateParsers: Map<StateKey<K>, StateRV<K, WS_C>>;
  skipWs: SkipWs<K, WS_C>;

  logic<T extends (...args: any[]) => any = FnT<K, WS_C>>(closure: T, resources: Resources): Fn<T>;
};

interface RuntimeCtx<K extends StateName, WS_C> {
  readonly input: string;

  getMemo(state: StateKey<K>, pos: number): MemoEntry | undefined;
  setMemo(state: StateKey<K>, pos: number, entry: MemoEntry): void;

  readonly ws: WS_C;
};

export function improves(next: Result, prev: Result): boolean {
  return next.ok && (!prev.ok || next.pos > prev.pos);
}

export function improves_error(next: Result, prev: Result): boolean {
  return !prev.ok && !next.ok && (
    next.pos > prev.pos ||
    (prev.type === 'none' && next.pos >= prev.pos)
  );
}
export function skipWs(rc: RuntimeCtx<StateName, { re: RegExp, last: number }>, pos: number): [ws: MatcherValue | null, pos: number] {
  if (rc.ws.last === pos) return [null, pos];
  const re = rc.ws.re;
  re.lastIndex = pos;
  const match = re.exec(rc.input);
  if (match) {
    let ws = match[0];
    pos += ws.length;
    rc.ws.last = pos;
    return [ws, pos];
  }
  rc.ws.last = pos;
  return [null, pos];
};

export type FnT<K extends StateName, WS_C, R = Result> = (rc: RuntimeCtx<K, WS_C>, pos: number) => R;
export type RV<K extends StateName, WS_C> = Fn<FnT<K, WS_C>>;
export type StateRV<K extends StateName, WS_C> = Fn<FnT<K, WS_C, Result & { type: 'state' }>>;
function buildState<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  state: StateKey<K>
): StateRV<K, WS_C> {
  const sid = ctx.sccOf.get(state);
  if (sid === undefined) {
    const x = buildStateBody(ctx, state, ctx.lexicalStates.has(state));
    return ctx.logic((rc, pos) => {
      const existing = rc.getMemo(state, pos);
      if (existing) {
        const result = existing.result;
        return { type: 'state', ok: result.ok, pos: result.pos, value: result, state };
      }

      const result = x(rc, pos);
      rc.setMemo(state, pos, { result });
      return { type: 'state', ok: result.ok, pos: result.pos, value: result, state };
    }, { x, state });
  }

  const s = buildSCC(ctx, sid);
  return ctx.logic((rc, pos) => {
    const existing = rc.getMemo(state, pos);
    if (existing) {
      const result = existing.result;
      return { type: 'state', ok: result.ok, pos: result.pos, value: result, state };
    }

    s(rc, pos);

    const entry = rc.getMemo(state, pos);
    if (!entry)
      throw new Error(`Internal error: No result generated by solveSCC`, { cause: { state, entry, pos } });

    const result = entry.result;
    return { type: 'state', ok: result.ok, pos: result.pos, value: result, state };
  }, { s, state });
}

function buildSCC<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  sccId: SccId
): Fn<FnT<K, WS_C, void>> {
  const cached = ctx.sccSolvers.get(sccId);
  if (cached) return cached;

  const group = ctx.sccMembers.get(sccId);
  if (!group || group.length === 0)
    throw new Error(`Internal error: invalid scc group for ${sccId}`, { cause: { ctx, sccId, group } });

  let ev: RV<K, WS_C>[] = [];
  for (let i = 0; i < group.length; i++) {
    const st = group[i];
    const x = buildStateBody(ctx, st, ctx.lexicalStates.has(st));
    ev.push(x);
  }

  let result;
  if (ev.length === 1) {
    const x = ev[0];
    const st = group[0];
    result = ctx.logic((rc, pos) => {
      let entry = rc.getMemo(st, pos);
      if (!entry) {
        entry = { result: { type: 'none', ok: false, pos, value: null } };
        rc.setMemo(st, pos, entry);
      }
      while (true) {
        const candidate = x(rc, pos);
        if (improves(candidate, entry.result)) {
          entry.result = candidate;
        } else if (improves_error(candidate, entry.result)) {
          entry.result = candidate;
          return;
        } else return;
      }
    }, { x, st });
  } else {
    result = ctx.logic((rc, pos) => {
      let entries: MemoEntry[] = Array(group.length);
      for (let i = 0; i < group.length; i++) {
        const st = group[i];
        let memo = rc.getMemo(st, pos);
        if (!memo) {
          memo = { result: { type: 'none', ok: false, pos, value: null } };
          rc.setMemo(st, pos, memo);
        }
        entries[i] = memo;
      }
      let changed = true;
      while (changed) {
        changed = false;

        for (let i = 0; i < group.length; i++) {
          const entry = entries[i];
          const candidate = ev[i](rc, pos);

          if (improves(candidate, entry.result)) {
            entry.result = candidate;
            changed = true;
          } else if (improves_error(candidate, entry.result)) {
            entry.result = candidate;
          }
        }
      }
    }, { ev, group });
  }

  ctx.sccSolvers.set(sccId, result);
  return result;
}

function buildStateBody<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  state: StateKey<K>,
  lexical: boolean
): RV<K, WS_C> {
  const seq = ctx.graph.get(state);
  if (!seq)
    throw new Error(`Invalid state: ${state}`, { cause: { ctx, state } });

  return buildSequence(ctx, seq, lexical);
}

function buildTerm<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  term: RegExp | StateKey<K> | Choice<K> | Sequence<K>,
  lexical: boolean
): RV<K, WS_C> {
  if (term instanceof RegExp) {
    const x = buildRegex(ctx, term);
    if (lexical)
      return x;
    const s = ctx.skipWs;
    return ctx.logic((rc, pos) => {
      let ws;
      [ws, pos] = s(rc, pos);
      const result = x(rc, pos);
      if (ws) result.ws = result.ws ? ws + result.ws : ws;
      return result;
    }, { x, s });
  } else if (term instanceof Sequence) {
    return buildSequence(ctx, term, lexical);
  } else if (term instanceof Choice) {
    return buildChoice(ctx, term, lexical);
  } else {
    const x = ctx.stateParsers.get(term)!;
    if (lexical)
      return x;
    const s = ctx.skipWs;
    return ctx.logic((rc, pos) => {
      let ws;
      [ws, pos] = s(rc, pos);
      const result = x(rc, pos);
      if (ws) result.ws = result.ws ? ws + result.ws : ws;
      return result;
    }, { x, s });
  }
}
const noop = logic<FnT<StateName, unknown, never>>((rc, pos) => {
  throw new Error('Internal Error: noop reached.', { cause: { rc, pos } });
}, {});

function buildSequence<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  seq: Sequence<K>,
  lexical: boolean
): RV<K, WS_C> {
  const { body } = seq.segments;
  lexical = lexScope(ctx, seq, lexical);
  let r: RV<K, WS_C>;
  if (body.length === 1) {
    const term = body[0];
    throwOnGeneric(term);
    const x = buildTerm(ctx, term, lexical);
    r = ctx.logic((rc, pos) => {
      const r = x(rc, pos);
      return { type: 'sequence', ok: r.ok, pos: r.pos, value: [r] };
    }, { x });
  } else {
    const ev: RV<K, WS_C>[] = [];
    for (const term of body) {
      throwOnGeneric(term);
      const x = buildTerm(ctx, term, lexical);
      ev.push(x);
    }
    r = ctx.logic((rc, pos) => {
      let curPos = pos;
      let results: Result[] = [];
      for (const x of ev) {
        const r: Result = x(rc, curPos);
        results.push(r); curPos = r.pos;
        if (!r.ok)
          return { type: 'sequence', ok: false, pos: curPos, value: results };
      }
      return { type: 'sequence', ok: true, pos: curPos, value: results };
    }, { ev });
  }
  return withOperators(ctx, seq, r, lexical);
}

function buildChoice<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  choice: Choice<K>,
  lexical: boolean
): RV<K, WS_C> {
  const { ops, body } = choice.segments;
  lexical = lexScope(ctx, choice, lexical);
  let r: RV<K, WS_C>;
  if (body.length === 1) {
    const term = body[0];
    throwOnGeneric(term);
    const x = buildTerm(ctx, term, lexical);
    r = ctx.logic((rc, pos) => {
      const r = x(rc, pos);
      return { type: 'choice', ok: r.ok, pos: r.pos, value: r, alt: 0 };
    }, { x });
  } else {
    const ev: RV<K, WS_C>[] = [];
    for (const term of body) {
      throwOnGeneric(term);
      const x = buildTerm(ctx, term, lexical);
      ev.push(x);
    }
    const hasOrderedChoice = ops.has('/');
    if (hasOrderedChoice)
      r = ctx.logic((rc, pos) => {
        let error: Result = { type: 'none', ok: false, pos, value: null };
        let errorId: number | null = null;
        for (let i = 0; i < ev.length; i++) {
          const alt = ev[i];
          const r = alt(rc, pos);
          if (r.ok)
            return { type: 'choice', ok: r.ok, pos: r.pos, value: r, alt: i };
          if (improves_error(r, error)) {
            error = r;
            errorId = i;
          }
        }
        return { type: 'choice', ok: error.ok, pos: error.pos, value: error, alt: errorId };
      }, { ev });
    else
      r = ctx.logic((rc, pos) => {
        let best: Result = { type: 'none', ok: false, pos, value: null };
        let bestId: number | null = null;
        for (let i = 0; i < ev.length; i++) {
          const alt = ev[i];
          const r = alt(rc, pos);
          if (improves(r, best)) {
            best = r;
            bestId = i;
          } else if (improves_error(r, best)) {
            best = r;
            bestId = i;
          }
        }
        return { type: 'choice', ok: best.ok, pos: best.pos, value: best, alt: bestId };
      }, { ev });
  }
  return withOperators(ctx, choice, r, lexical);
}

function buildRegex<K extends StateName, WS_C>(ctx: ParserCtx<K, WS_C>, re: RegExp): RV<K, WS_C> {
  if (!re.sticky || re.global)
    throw new Error(`matchRegex: Expected sticky and non-global regex, got: ${re.flags}`, { cause: re });

  return ctx.logic((rc, pos) => {
    re.lastIndex = pos;
    const m = re.exec(rc.input);

    if (!m) return { type: 'terminal', ok: false, pos, value: null };
    const value = m[0];
    return { type: 'terminal', ok: true, pos: pos + value.length, value };
  }, { re });
}

function throwOnGeneric<K extends StateName>(x: Exclude<GraphToken<K>, StandaloneOperator> | Generic):
  asserts x is Exclude<GraphToken<K>, StandaloneOperator> {
  if (isGeneric(x))
    throw new Error(
      'Generic states must be referenced using a CallToken, not as plain state references.',
      { cause: x }
    );
}

function lexScope<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  data: GraphCollection<K>,
  lexical: boolean
): boolean {
  const { ops } = data.segments;

  const hasLex = ops.has('#');
  const hasSyn = ops.has('%');

  if (hasLex) lexical = true;
  else if (hasSyn) lexical = false;

  return lexical;
}

function withOperators<K extends StateName, WS_C>(
  ctx: ParserCtx<K, WS_C>,
  data: GraphCollection<K>,
  r: RV<K, WS_C>,
  lexical: boolean
): RV<K, WS_C> {
  const { ops } = data.segments;

  const hasPosLA = ops.has('&');
  const hasNegLA = ops.has('!');
  const hasStar = ops.has('*');
  const hasPlus = ops.has('+');
  const hasOpt = ops.has('?');
  const hasAt = ops.has('@');
  const hasRewind = ops.has('$');

  const s = ctx.skipWs;
  if (hasAt) {
    const x = r;
    r = lexical ? ctx.logic((rc, pos) => {
      const r = x(rc, pos);
      return {
        type: 'iteration',
        ok: r.ok,
        pos: hasRewind ? (r.ok ? r.pos : pos) : r.pos,
        value: [r],
        kind: '@'
      };
    }, { x, hasRewind }) : ctx.logic((rc, pos) => {
      let [ws, runPos] = s(rc, pos);
      const r = x(rc, runPos);
      return {
        type: 'iteration',
        ok: r.ok,
        pos: hasRewind ? (r.ok ? r.pos : pos) : r.pos,
        value: [r],
        kind: '@',
        ws
      };
    }, { x, hasRewind, s });
  } else if (hasOpt) {
    const x = r;
    r = lexical ? ctx.logic((rc, pos) => {
      const r = x(rc, pos);
      if (!r.ok && (hasRewind || r.pos === pos))
        return {
          type: 'iteration',
          ok: true,
          pos, value: [],
          kind: '?'
        };
      else
        return {
          type: 'iteration',
          ok: r.ok,
          pos: r.pos,
          value: [r],
          kind: '?'
        };
    }, { x, hasRewind }) : ctx.logic((rc, pos) => {
      let [ws, runPos] = s(rc, pos);
      const r = x(rc, runPos);
      if (!r.ok && (hasRewind || r.pos === runPos))
        return {
          type: 'iteration',
          ok: true,
          pos, value: [],
          kind: '?'
        };
      else
        return {
          type: 'iteration',
          ok: r.ok,
          pos: r.pos,
          value: [r],
          kind: '?',
          ws
        };
    }, { x, hasRewind, s });
  } else if (hasStar) {
    const x = r;
    r = lexical ? ctx.logic((rc, pos) => {
      const results: Result[] = [];
      let curPos = pos;

      while (true) {
        const r = x(rc, curPos);
        if (r.pos === curPos) break;
        if (hasRewind && !r.ok) break;

        results.push(r);
        curPos = r.pos;
        if (!r.ok) break;
      }

      return {
        type: 'iteration',
        ok: results.length ? results[results.length - 1].ok : true,
        pos: curPos,
        value: results,
        kind: '*'
      };
    }, { x, hasRewind }) : ctx.logic((rc, pos) => {
      const results: Result[] = [];
      let curPos = pos;

      while (true) {
        let [ws, runPos] = s(rc, curPos);
        const r = x(rc, runPos);
        if (ws) r.ws = r.ws ? ws + r.ws : ws;

        if (r.pos === runPos) break;
        if (hasRewind && !r.ok) break;
        results.push(r);
        curPos = r.pos;
        if (!r.ok) break;
      }

      return {
        type: 'iteration',
        ok: results.length ? results[results.length - 1].ok : true,
        pos: curPos,
        value: results,
        kind: '*'
      };
    }, { x, hasRewind, s });
  } else if (hasPlus) {
    const x = r;
    r = lexical ? ctx.logic((rc, pos) => {
      const results: Result[] = [];
      let curPos = pos;

      while (true) {
        const r = x(rc, curPos);
        if (results.length) {
          if (r.pos === curPos) break;
          if (hasRewind && !r.ok) break;
        }
        results.push(r);
        curPos = r.pos;
        if (!r.ok) break;
      }

      return {
        type: 'iteration',
        ok: results.length ? results[results.length - 1].ok : true,
        pos: curPos,
        value: results,
        kind: '+'
      };
    }, { x, hasRewind }) : ctx.logic((rc, pos) => {
      const results: Result[] = [];
      let curPos = pos;

      while (true) {
        let [ws, runPos] = s(rc, curPos);
        const r = x(rc, runPos);
        if (ws) r.ws = r.ws ? ws + r.ws : ws;

        if (results.length) {
          if (r.pos === runPos) break;
          if (hasRewind && !r.ok) break;
        }
        results.push(r);
        curPos = r.pos;
        if (!r.ok) break;
      }

      return {
        type: 'iteration',
        ok: results.length ? results[results.length - 1].ok : true,
        pos: curPos,
        value: results,
        kind: '+'
      };
    }, { x, hasRewind, s });
  }

  // --- rewind ---
  if (hasRewind && !hasAt && !hasOpt && !hasStar && !hasPlus) {
    const x = r;
    r = ctx.logic((rc, pos) => {
      const result = x(rc, pos);
      return {
        type: 'rewind',
        ok: result.ok,
        pos: result.ok ? result.pos : pos,
        value: result
      }
    }, { x });
  }

  // --- lookahead ---
  if (hasPosLA) {
    const x = r;
    r = ctx.logic((rc, pos) => {
      const result = x(rc, pos);
      return {
        type: 'lookahead',
        ok: result.ok,
        pos,
        value: result,
        positive: true
      }
    }, { x });
  } else if (hasNegLA) {
    const x = r;
    r = ctx.logic((rc, pos) => {
      const result = x(rc, pos);
      return {
        type: 'lookahead',
        ok: !result.ok,
        pos,
        value: result,
        positive: false
      }
    }, { x });
  }

  return r;
}

const WS_REGEX = /\s+/y;
const LEXICAL_REGEX = /^[\p{Ll}_]/u;
export type ParserFn<
  K extends StateName, WS_I extends any[] = DefaultSkipWsInput, WS_O = DefaultSkipWsOutput
> = (input: string, start: StateKey<K>, ...args: WS_I) => Result & { type: 'root'; };
type ParserResources<K extends StateName, WS_I extends any[], WS_O> = {
  states: Map<StateKey<K>, StateRV<K, WS_O>>,
  allStates: Set<StateKey<K>>,
  lexicalStates: Set<StateKey<K>>,
  processWSArgs: (...args: WS_I) => WS_O,
  s: SkipWs<K, WS_O>
};
export type Parser<
  K extends StateName, WS_I extends any[] = DefaultSkipWsInput, WS_O = DefaultSkipWsOutput
> = Fn<ParserFn<K, WS_I, WS_O>> & { resources: ParserResources<K, WS_I, WS_O> };
export type SkipWsBuilder<K extends StateName, I extends any[], O> = (states: MapView<StateKey<K>, StateRV<K, O> | FnT<K, O>>) => {
  skipWs: SkipWsFn<K, O>;
  processArgs: (...args: I) => O,
  resources?: Resources;
};

type DefaultSkipWsInput = [ws?: RegExp];
type DefaultSkipWsOutput = { re: RegExp, last: number };
type DefaultSkipWsBuilder = SkipWsBuilder<StateName, DefaultSkipWsInput, DefaultSkipWsOutput>;
export function defaultSkipWsBuilder(...params: Parameters<DefaultSkipWsBuilder>): ReturnType<DefaultSkipWsBuilder>;
export function defaultSkipWsBuilder(): ReturnType<DefaultSkipWsBuilder> {
  return {
    skipWs,
    processArgs(ws?: RegExp) {
      ws ??= WS_REGEX;
      if (!ws.sticky || ws.global) {
        throw new Error("Whitespace regex must be sticky and non-global");
      }
      return { re: ws, last: -1 };
    },
    resources: { WS_REGEX }
  }
}

export function build<K extends StateName>(
  graph: Graph<K>,
  metadata: true
): Parser<K, DefaultSkipWsInput, DefaultSkipWsOutput>;
export function build<K extends StateName>(
  graph: Graph<K>,
  metadata?: false
): ParserFn<K, DefaultSkipWsInput, DefaultSkipWsOutput>;
export function build<K extends StateName>(
  graph: Graph<K>,
  metadata: boolean
): ParserFn<K, DefaultSkipWsInput, DefaultSkipWsOutput> | Parser<K, DefaultSkipWsInput, DefaultSkipWsOutput>;

export function build<K extends StateName, WS_I extends any[], WS_O>(
  graph: Graph<K>,
  metadata: true,
  makeSkipWs: SkipWsBuilder<K, WS_I, WS_O>
): Parser<K, WS_I, WS_O>;
export function build<K extends StateName, WS_I extends any[], WS_O>(
  graph: Graph<K>,
  metadata: false,
  makeSkipWs: SkipWsBuilder<K, WS_I, WS_O>
): ParserFn<K, WS_I, WS_O>;
export function build<K extends StateName, WS_I extends any[], WS_O>(
  graph: Graph<K>,
  metadata: boolean,
  makeSkipWs: SkipWsBuilder<K, WS_I, WS_O>
): ParserFn<K, WS_I, WS_O> | Parser<K, WS_I, WS_O>;

export function build<K extends StateName, WS_I extends any[], WS_O>(
  graph: Graph<K>,
  metadata = false,
  makeSkipWs: SkipWsBuilder<K, WS_I, WS_O> = defaultSkipWsBuilder as any
): ParserFn<K, WS_I, WS_O> | Parser<K, WS_I, WS_O> {
  const lexicalStates = new Set<StateKey<K>>();
  const allStates = new Set(graph.keys());
  for (const stateLabel of allStates) {
    if (LEXICAL_REGEX.test(stateLabel))
      lexicalStates.add(stateLabel);
  }

  const ctx: ParserCtx<K, WS_O> = {
    graph,
    sccOf: graph.sccOf,
    sccMembers: graph.sccMembers,
    sccSolvers: new Map(),
    lexicalStates,
    stateParsers: new Map(),
    skipWs: noop,
    logic(closure, resources) {
      if (metadata)
        return logic(closure, resources);
      return closure as unknown as Fn<typeof closure>;
    }
  };

  const states = new Map<StateKey<K>, StateRV<K, WS_O>>();
  const lazy = new Map<StateKey<K>, (val: StateRV<K, WS_O>) => void>();
  for (const [stateLabel, state] of graph.entries()) {
    if (state.generic) continue;
    let x: StateRV<K, WS_O> = noop;
    const f = ctx.logic(
      (rc, pos) => x(rc, pos), { x }
    );
    ctx.stateParsers.set(stateLabel, f);
    lazy.set(stateLabel,
      f.resources ? (val) => {
        x = val;
        f.resources.x = x;
      } : (val) => {
        x = val;
      });
  }

  const {
    skipWs: user_skipWs,
    resources: ws_resources,
    processArgs: ws_processArgs
  } = makeSkipWs(new MapView(ctx.stateParsers));
  if (!user_skipWs)
    throw new Error('skipWsBuilder must return { skipWs, processArgs, resources? } but is missing skipWs');
  ctx.skipWs = ctx.logic(user_skipWs, ws_resources ?? {});
  if (!ws_processArgs)
    throw new Error('skipWsBuilder must return { skipWs, processArgs, resources? } but is missing processArgs');
  const processWSArgs = ctx.logic(ws_processArgs, ws_resources ?? {});

  for (const [stateLabel, state] of graph.entries()) {
    if (state.generic) continue;
    states.set(stateLabel, buildState(ctx, stateLabel));
  }

  for (const [stateLabel, cb] of lazy.entries()) {
    cb(states.get(stateLabel)!);
  }

  const s = ctx.skipWs;
  const parse: ParserFn<K, WS_I, WS_O> = (input, start, ...ws_args: WS_I) => {
    const ws_c = processWSArgs(...ws_args);

    const x = states.get(start);
    if (!x && allStates.has(start))
      throw new Error(`Cannot start at generic state: ${start}`, { cause: { input, start } });
    if (!x)
      throw new Error(`Cannot start at unknown state: ${start}`, { cause: { input, start } });

    const memos = new Map<StateKey<K>, Map<number, MemoEntry>>();
    for (const stateLabel of states.keys()) {
      memos.set(stateLabel, new Map);
    }

    const rc: RuntimeCtx<K, WS_O> = {
      input,

      getMemo(state, pos) {
        return memos.get(state)!.get(pos);
      },
      setMemo(state, pos, entry) {
        memos.get(state)!.set(pos, entry);
      },

      ws: ws_c
    };

    const result = x(rc, 0);
    const lexical = lexicalStates.has(start);
    let trailing_ws = null, endPos = result.pos;
    if (!lexical) {
      [trailing_ws, endPos] = s(rc, result.pos);
    }

    if (result.ok && endPos === input.length) {
      return {
        type: 'root',
        ok: true, pos: endPos, value: result,
        trailing_ws
      };
    }

    return {
      type: 'root',
      ok: false, pos: endPos, value: result,
      trailing_ws
    };
  };
  if (metadata)
    return ctx.logic(parse, { states, allStates, lexicalStates, processWSArgs, s } satisfies ParserResources<K, WS_I, WS_O>);
  return parse;
}
